# Generated by Django 3.1.6 on 2021-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='professor',
            new_name='professors',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
    ]
