# Generated by Django 3.1.6 on 2021-02-13 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalita', '0002_auto_20210213_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='coherence',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalita.course'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='easiness',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='general',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalita.student'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='understanding',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
